source :rubygems
gem 'sinatra'
gem 'haml'
gem 'ruby-openid', '>=2.1.2'
gem 'builder'
gem 'maruku'
gem 'dm-core'
gem 'dm-tags'
gem 'dm-migrations'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-sqlite-adapter'
